name: test
on:
  push:
    paths:
      - Formula/**.rb
    branches:
      - main
  pull_request:
    paths:
      - Formula/**.rb
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "The version of Bun to install. Can be left empty."
        type: string
        required: false
jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-homebrew
        name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master # no releases? :(
      - id: setup-tap
        name: Setup Tap
        run: brew tap oven-sh/bun ./
      - id: install-bun
        name: Install Bun
        run: brew install bun
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.version == ''
      - id: install-versioned-bun
        name: Install Versioned Bun
        run: brew install bun@${{ github.event.inputs.version }}
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
      - id: run-bun
        name: Run Bun
        run: bun -v
      - id: uninstall-bun
        name: Uninstall Bun
        run: brew uninstall bun
      - id: teardown-tap
        name: Teardown Tap
        run: brew untap oven-sh/bun
